name: Deploy site to Cloudflare Pages

on:
  push:
    branches: ["main"]
    paths:
      - "site/**"
      - ".github/workflows/deploypages.yaml"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write # Infisical OIDC auth

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.16
        with:
          domain: "https://eu.infisical.com"
          method: "oidc"
          env-slug: "ci"
          project-slug: "cicd"
          identity-id: "4d6a4fd3-8b48-4eab-86a9-37d87de683e0"
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.cloudflare_api_token }}
          accountId: ${{ env.cloudflare_account_id }}
          command: pages deploy site --project-name=agent-skills-validator
          githubToken: ${{ secrets.GITHUB_TOKEN }}
